# ndarry的索引(index),切割(slice)

In [4]:
import numpy as np

arr = np.arange(10)
arr[0]
arr[-1]
arr[:3]
arr[-3:]

array([7, 8, 9])

In [5]:
import random
random.randint(50,100)

85

In [11]:
np.random.randint(50, 101, size=5)
scores = np.random.randint(50,101, size=(50, 5))
scores.size
scores.shape

(50, 5)

In [14]:
scores[:,0]
scores[:,0:1]

array([[52],
       [73],
       [82],
       [61],
       [62],
       [69],
       [67],
       [81],
       [76],
       [56],
       [79],
       [65],
       [84],
       [83],
       [97],
       [74],
       [92],
       [90],
       [69],
       [73],
       [51],
       [98],
       [59],
       [74],
       [98],
       [86],
       [64],
       [92],
       [86],
       [65],
       [87],
       [96],
       [78],
       [68],
       [91],
       [50],
       [89],
       [54],
       [97],
       [89],
       [72],
       [97],
       [94],
       [51],
       [89],
       [65],
       [83],
       [70],
       [71],
       [66]])

In [17]:
scores[0,:]
scores[0:1,:]

array([[52, 92, 57, 72, 83]])

In [21]:
np.sum(scores,axis=1)
np.mean(scores, axis=1)

array([71.2, 72. , 75.2, 78. , 75.2, 80. , 71.2, 81. , 76.2, 74.4, 78.2,
       79.2, 80.4, 78.2, 87.2, 74.6, 77. , 80. , 85.6, 77.6, 68.4, 88. ,
       79. , 73. , 79. , 83.2, 64.8, 89.8, 78.2, 68.6, 79.6, 80.8, 87.4,
       67. , 87.2, 63.8, 77.4, 73.2, 68.2, 72.4, 75. , 89.2, 78.6, 72. ,
       78. , 83.8, 76.8, 64.2, 76.8, 63.2])