https://www.perplexity.ai/search/1f6d8098-e981-44bf-b915-b14b9e9052da

In [2]:
import numpy as np
np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [3]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [6]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [7]:
np.random.rand(3, 4)

array([[0.6229407 , 0.80029474, 0.39864527, 0.14802886],
       [0.84010517, 0.22241847, 0.66698675, 0.84342453],
       [0.36296261, 0.40864043, 0.08221354, 0.36211242]])

In [ ]:
scores = np.random.randint(50,101,size=(50, 5))

array([[ 76,  83,  66,  50,  89],
       [ 52,  75,  68,  62,  84],
       [ 70,  65,  86,  67,  84],
       [ 98,  73,  63,  82,  89],
       [ 60,  70,  95,  79,  60],
       [ 82,  54,  60,  70,  51],
       [ 68,  71,  58,  56,  59],
       [ 57,  95,  58,  80,  63],
       [ 71,  84,  56,  94,  74],
       [ 72,  60,  89,  85,  59],
       [ 51,  91,  63,  51,  75],
       [ 75,  57,  50,  76,  85],
       [ 59,  70,  61,  68,  73],
       [ 61,  78,  50,  64,  98],
       [ 56,  79,  50,  81,  58],
       [ 85, 100,  92,  86,  85],
       [ 73,  99,  79,  73,  96],
       [ 73,  53,  78,  78,  77],
       [ 58,  70,  60,  56,  72],
       [ 77,  81,  79,  77,  59],
       [ 88,  78,  96,  84,  85],
       [ 51,  84,  72,  55,  51],
       [ 85,  89,  87,  89,  93],
       [ 63,  80,  80,  83,  98],
       [ 76,  81,  93,  63,  79],
       [ 59, 100,  98,  61,  79],
       [ 70,  96,  82, 100,  84],
       [ 68,  73,  80,  89,  73],
       [ 56,  51,  76,  94,  60],
       [ 82,  