https://www.perplexity.ai/search/27854047-0059-44b3-b1ed-b6dbdddd6505

In [3]:
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[58, 91, 72, 62, 99],
       [82, 59, 53, 67, 57],
       [74, 79, 79, 58, 79],
       [63, 82, 58, 76, 93],
       [61, 83, 61, 94, 72]])

In [4]:
scores[:3,2:]

array([[72, 62, 99],
       [53, 67, 57],
       [79, 58, 79]])

In [10]:
scores[4]
scores[4,:]
scores[4:,:]

array([[61, 83, 61, 94, 72]])

In [11]:
scores[:,:2]

array([[58, 91],
       [82, 59],
       [74, 79],
       [63, 82],
       [61, 83]])