https://www.perplexity.ai/search/27854047-0059-44b3-b1ed-b6dbdddd6505

### numpy的索引和切割

In [3]:
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[58, 91, 72, 62, 99],
       [82, 59, 53, 67, 57],
       [74, 79, 79, 58, 79],
       [63, 82, 58, 76, 93],
       [61, 83, 61, 94, 72]])

In [4]:
scores[:3,2:]

array([[72, 62, 99],
       [53, 67, 57],
       [79, 58, 79]])

In [10]:
scores[4]
scores[4,:]
scores[4:,:]

array([[61, 83, 61, 94, 72]])

In [11]:
scores[:,:2]

array([[58, 91],
       [82, 59],
       [74, 79],
       [63, 82],
       [61, 83]])

### numpy的統計工具

In [12]:
scores = np.random.randint(50,101,size=(5,5))
scores

array([[ 95,  88,  86,  67,  51],
       [ 74,  72, 100,  95,  63],
       [ 97,  73,  91,  59,  85],
       [ 91,  51,  54,  75,  66],
       [ 91,  93,  83,  65,  59]])

In [13]:
scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]

array([387, 404, 405, 337, 391])

In [ ]:
#加總
np.sum(scores,axis=1)

array([387, 404, 405, 337, 391])

In [15]:
#平均
np.mean(scores, axis=1)

array([77.4, 80.8, 81. , 67.4, 78.2])

In [16]:
#最大
np.max(scores,axis=1)

array([ 95, 100,  97,  91,  93])

In [17]:
#最小
np.min(scores,axis=1)

array([51, 63, 59, 51, 59])

In [18]:
#中間數
np.median(scores,axis=1)

array([86., 74., 85., 66., 83.])

In [19]:
#標準差
np.std(scores,axis=1)

array([16.13195586, 14.21829807, 13.56465997, 14.59588983, 13.77534029])